modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/neapolitan/issues"
license = "https://github.com/team-abnormals/neapolitan/blob/main/LICENSE.txt"

[[mods]]
    modId = "neapolitan"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "bageldotjpg & five"
    displayName = "Neapolitan"
    description = '''
    Adds new flavors and fruits to create tasty Ice Creams, Milkshakes, Cakes, and more!
    '''

[[dependencies.neapolitan]]
    modId = "forge"
    mandatory = true
    versionRange = "[32.0.72,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.neapolitan]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.1]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.neapolitan]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[2.0.7,)"
    ordering = "AFTER"
    side = "BOTH"
