modLoader="javafml"
loaderVersion="[31,)"
logoFile="logo.png"
authors="bageldotjpg"
credits="my mom"

[[mods]]
    modId="neapolitan"
    version="${file.jarVersion}"
    displayName="Neapolitan"
    description='''
    INSERT DESCRIPTION HERE
    '''

[[dependencies.neapolitan]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.49,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.neapolitan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.neapolitan]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.5,)"
    ordering="AFTER"
    side="BOTH"