modLoader="javafml"
loaderVersion="[32,)"
logoFile="logo.png"
authors="bageldotjpg"
credits="my mom"

[[mods]]
    modId="neapolitan"
    version="${file.jarVersion}"
    displayName="Neapolitan"
    description='''
    INSERT DESCRIPTION HERE
    '''

[[dependencies.neapolitan]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.88,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.neapolitan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.neapolitan]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"